version: '3'
services:
  backend:
    build: .
    container_name: "phonepe-alertmonitor"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb:27017/alertmonitor"  # Update the MongoDB URL accordingly

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGO_DBNAME: alertmonitor  # Update the database name accordingly

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

