apiVersion: v1
kind: Pod
metadata:
  name: alertmonitor
  namespace: alertmonitor
spec:
  containers:
  - name: phonepe-alertmonitor 
    image: parikshit3097/phonepe-alertmonitor 
    ports:
    - containerPort: 8080

