apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: alertmonitor
spec:
  selector:
    app: alertmonitor
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30009

---
apiVersion: v1
kind: Service
metadata:
  name: alertmonitor-service
  namespace: alertmonitor
spec:
  selector:
    app: alertmonitor
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: alertmonitor
spec:
  selector:
    app: alertmonitor
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30005

